name: Build CI docker image
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    name: "Build and push CI Docker image"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout this repository"
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
      - name: "Log in to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push CI Docker image"
        uses: docker/build-push-action@v4
        with:
          context: ./custom-ci-docker
          file: ./custom-ci-docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/opensearch-ci-docker:latest
